services:
  db:
    image: postgres:16
    container_name: menuapp_db
    environment:
      POSTGRES_DB: menuapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - menuapp_pgdata:/var/lib/postgresql/data

volumes:
  menuapp_pgdata:
